@extends('admin.layouts.app')

@section('title', 'Worksheet Rekonsiliasi')

@section('content')

{{-- 
    DATA UNTUK ALPINE JS
    Kita kirim data transaksi dari PHP ke Javascript object agar bisa dihitung real-time.
--}}
@php
    // Gabungkan data cleared & unreconciled jadi satu array untuk JS
    // Tambahkan flag 'cleared' = true/false
    
    $allDeposits = collect();
    $allPayments = collect();

    // DEPOSITS (Debit)
    foreach($cleared_deposits as $d) { 
        $d->is_cleared = true; $d->amount = $d->debit; $allDeposits->push($d); 
    }
    foreach($unreconciled_deposits as $d) { 
        $d->is_cleared = false; $d->amount = $d->debit; $allDeposits->push($d); 
    }

    // PAYMENTS (Credit)
    foreach($cleared_payments as $p) { 
        $p->is_cleared = true; $p->amount = $p->credit; $allPayments->push($p); 
    }
    foreach($unreconciled_payments as $p) { 
        $p->is_cleared = false; $p->amount = $p->credit; $allPayments->push($p); 
    }
@endphp

<div x-data="reconWorksheet()" class="flex flex-col gap-6 h-full">

    {{-- HEADER & SUMMARY CARDS (Sticky Top) --}}
    <div class="sticky top-0 z-20 bg-slate-50/95 dark:bg-[#0f172a]/95 backdrop-blur shadow-sm pb-4 pt-2 -mx-6 px-6 sm:-mx-8 sm:px-8 border-b border-slate-200 dark:border-slate-800 transition-all">
        
        <div class="flex flex-col xl:flex-row xl:items-center justify-between gap-4 mb-4">
            <div>
                <a href="{{ route('admin.bank-reconciliations.index') }}" class="flex items-center gap-2 text-slate-500 hover:text-indigo-600 transition-colors w-fit mb-1 text-xs font-bold uppercase tracking-wider">
                    <i class="material-icons text-sm">arrow_back</i> Kembali
                </a>
                <h1 class="text-xl font-bold text-slate-800 dark:text-white flex items-center gap-2">
                    Rekonsiliasi: {{ $bankReconciliation->account->account_name }}
                    <span class="badge {{ $bankReconciliation->status == 'reconciled' ? 'badge-success' : 'badge-warning' }} text-xs">
                        {{ ucfirst($bankReconciliation->status) }}
                    </span>
                </h1>
                <p class="text-xs text-slate-500">Per Tanggal: {{ $bankReconciliation->statement_date->format('d F Y') }}</p>
            </div>

            {{-- ACTION BUTTONS --}}
            <div class="flex gap-3">
                @if($bankReconciliation->status == 'draft')
                    <form id="save-draft-form" action="{{ route('admin.bank-reconciliations.update', $bankReconciliation->reconciliation_id) }}" method="POST">
                        @csrf @method('PUT')
                        {{-- Hidden inputs generated by Alpine --}}
                        <template x-for="id in getClearedIds()">
                            <input type="hidden" name="cleared_entries[]" :value="id">
                        </template>
                        <input type="hidden" name="action" value="save_draft">
                        
                        <button type="submit" class="btn btn-secondary">
                            <i class="material-icons text-sm mr-2">save</i> Simpan Draft
                        </button>
                    </form>

                    <form id="finish-recon-form" action="{{ route('admin.bank-reconciliations.update', $bankReconciliation->reconciliation_id) }}" method="POST">
                        @csrf @method('PUT')
                        <template x-for="id in getClearedIds()">
                            <input type="hidden" name="cleared_entries[]" :value="id">
                        </template>
                        <input type="hidden" name="action" value="reconcile">

                        {{-- Disable button if difference != 0 --}}
                        <button type="button" @click="submitFinish()" class="btn btn-primary" :class="{'opacity-50 cursor-not-allowed': Math.abs(difference) > 0.01}" :disabled="Math.abs(difference) > 0.01">
                            <i class="material-icons text-sm mr-2">check_circle</i> Selesai & Kunci
                        </button>
                    </form>
                @endif
            </div>
        </div>

        {{-- SUMMARY BOXES (CALCULATED BY ALPINE) --}}
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
            
            {{-- 1. Target (Statement) --}}
            <div class="bg-white dark:bg-slate-800 p-3 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm">
                <div class="text-[10px] uppercase font-bold text-slate-400">Saldo Rekening Koran</div>
                <div class="text-lg font-bold text-slate-800 dark:text-white" x-text="formatRupiah(statementBalance)"></div>
            </div>

            {{-- 2. Cleared Balance (Calculated) --}}
            <div class="bg-white dark:bg-slate-800 p-3 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm relative overflow-hidden">
                <div class="text-[10px] uppercase font-bold text-slate-400">Saldo Dicocokkan (Sistem)</div>
                <div class="text-lg font-bold text-indigo-600 dark:text-indigo-400" x-text="formatRupiah(clearedBalance)"></div>
                
                {{-- Mini detail --}}
                <div class="flex gap-2 text-[9px] text-slate-400 mt-1">
                    <span>In: <span class="text-emerald-500" x-text="formatRupiah(totalClearedDeposits)"></span></span>
                    <span>Out: <span class="text-rose-500" x-text="formatRupiah(totalClearedPayments)"></span></span>
                </div>
            </div>

            {{-- 3. Difference (THE GOAL) --}}
            <div class="p-3 rounded-lg border shadow-sm transition-colors duration-300"
                 :class="Math.abs(difference) < 0.01 ? 'bg-emerald-50 border-emerald-200' : 'bg-rose-50 border-rose-200'">
                <div class="text-[10px] uppercase font-bold"
                     :class="Math.abs(difference) < 0.01 ? 'text-emerald-600' : 'text-rose-600'">
                    Selisih (Harus 0)
                </div>
                <div class="text-lg font-extrabold"
                     :class="Math.abs(difference) < 0.01 ? 'text-emerald-700' : 'text-rose-700'"
                     x-text="formatRupiah(difference)">
                </div>
            </div>

            {{-- 4. Status GL --}}
            <div class="bg-slate-50 dark:bg-slate-800/50 p-3 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm">
                <div class="text-[10px] uppercase font-bold text-slate-400">Saldo Buku Besar</div>
                <div class="text-lg font-bold text-slate-600 dark:text-slate-300">{{ number_format($closingBalance, 0, ',', '.') }}</div>
            </div>

        </div>
    </div>

    {{-- WORKSHEET COLUMNS --}}
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 pb-20">
        
        {{-- COLUMN 1: DEPOSITS (Uang Masuk) --}}
        <div class="card h-full flex flex-col">
            <div class="card-header bg-emerald-50/50 dark:bg-emerald-900/10 border-b border-emerald-100 dark:border-emerald-800 justify-between">
                <h3 class="card-header-title text-emerald-800 dark:text-emerald-400">Pemasukan (Debit)</h3>
                <span class="text-xs font-mono font-bold text-emerald-600" x-text="formatRupiah(totalClearedDeposits)"></span>
            </div>
            <div class="flex-1 overflow-y-auto max-h-[600px] p-0 custom-scrollbar">
                <table class="w-full text-sm text-left">
                    <thead class="bg-slate-50 dark:bg-slate-800 text-xs text-slate-500 uppercase sticky top-0 z-10">
                        <tr>
                            <th class="w-10 px-4 py-2 text-center">✔</th>
                            <th class="px-4 py-2">Tgl</th>
                            <th class="px-4 py-2">Ref/Ket</th>
                            <th class="px-4 py-2 text-right">Jumlah</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100 dark:divide-slate-700">
                        <template x-for="row in deposits" :key="row.ledger_id">
                            <tr class="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors cursor-pointer"
                                :class="{'bg-emerald-50/30 dark:bg-emerald-900/10': row.is_cleared}"
                                @click="toggleRow(row)">
                                <td class="px-4 py-3 text-center">
                                    <input type="checkbox" x-model="row.is_cleared" class="rounded border-gray-300 text-emerald-600 focus:ring-emerald-500 cursor-pointer w-4 h-4">
                                </td>
                                <td class="px-4 py-3 whitespace-nowrap text-slate-500" x-text="formatDate(row.entry_date)"></td>
                                <td class="px-4 py-3">
                                    <div class="font-medium text-slate-700 dark:text-slate-200 line-clamp-1" x-text="row.description"></div>
                                    <div class="text-[10px] text-slate-400 font-mono" x-text="row.journal_group_id"></div>
                                </td>
                                <td class="px-4 py-3 text-right font-bold text-slate-700 dark:text-slate-300" x-text="formatNumber(row.amount)"></td>
                            </tr>
                        </template>
                        <tr x-show="deposits.length === 0">
                            <td colspan="4" class="text-center py-6 text-slate-500 italic">Tidak ada data pemasukan.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        {{-- COLUMN 2: PAYMENTS (Uang Keluar) --}}
        <div class="card h-full flex flex-col">
            <div class="card-header bg-rose-50/50 dark:bg-rose-900/10 border-b border-rose-100 dark:border-rose-800 justify-between">
                <h3 class="card-header-title text-rose-800 dark:text-rose-400">Pengeluaran (Kredit)</h3>
                <span class="text-xs font-mono font-bold text-rose-600" x-text="formatRupiah(totalClearedPayments)"></span>
            </div>
            <div class="flex-1 overflow-y-auto max-h-[600px] p-0 custom-scrollbar">
                <table class="w-full text-sm text-left">
                    <thead class="bg-slate-50 dark:bg-slate-800 text-xs text-slate-500 uppercase sticky top-0 z-10">
                        <tr>
                            <th class="w-10 px-4 py-2 text-center">✔</th>
                            <th class="px-4 py-2">Tgl</th>
                            <th class="px-4 py-2">Ref/Ket</th>
                            <th class="px-4 py-2 text-right">Jumlah</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100 dark:divide-slate-700">
                        <template x-for="row in payments" :key="row.ledger_id">
                            <tr class="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors cursor-pointer"
                                :class="{'bg-rose-50/30 dark:bg-rose-900/10': row.is_cleared}"
                                @click="toggleRow(row)">
                                <td class="px-4 py-3 text-center">
                                    <input type="checkbox" x-model="row.is_cleared" class="rounded border-gray-300 text-rose-600 focus:ring-rose-500 cursor-pointer w-4 h-4">
                                </td>
                                <td class="px-4 py-3 whitespace-nowrap text-slate-500" x-text="formatDate(row.entry_date)"></td>
                                <td class="px-4 py-3">
                                    <div class="font-medium text-slate-700 dark:text-slate-200 line-clamp-1" x-text="row.description"></div>
                                    <div class="text-[10px] text-slate-400 font-mono" x-text="row.journal_group_id"></div>
                                </td>
                                <td class="px-4 py-3 text-right font-bold text-slate-700 dark:text-slate-300" x-text="formatNumber(row.amount)"></td>
                            </tr>
                        </template>
                        <tr x-show="payments.length === 0">
                            <td colspan="4" class="text-center py-6 text-slate-500 italic">Tidak ada data pengeluaran.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

</div>

@push('scripts')
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('reconWorksheet', () => ({
            // State Data
            deposits: @json($allDeposits),
            payments: @json($allPayments),
            statementBalance: {{ $statementBalance }},
            openingBalance: {{ $calcOpeningBalance }}, // Kalkulasi Opening Balance Virtual

            // Computed Properties (via Getters)
            get totalClearedDeposits() {
                return this.deposits.filter(d => d.is_cleared).reduce((sum, d) => sum + parseFloat(d.amount), 0);
            },

            get totalClearedPayments() {
                return this.payments.filter(p => p.is_cleared).reduce((sum, p) => sum + parseFloat(p.amount), 0);
            },

            get clearedBalance() {
                // Rumus: Saldo Awal (Calculated) + Deposit Cleared - Payment Cleared
                return this.openingBalance + this.totalClearedDeposits - this.totalClearedPayments;
            },

            get difference() {
                // Selisih = Saldo Bank (Target) - Saldo Cleared (Sistem)
                return this.statementBalance - this.clearedBalance;
            },

            // Actions
            toggleRow(row) {
                // Jika status draft, bisa toggle. Jika reconciled, readonly.
                @if($bankReconciliation->status == 'draft')
                    row.is_cleared = !row.is_cleared;
                @endif
            },

            getClearedIds() {
                const depIds = this.deposits.filter(d => d.is_cleared).map(d => d.ledger_id);
                const payIds = this.payments.filter(p => p.is_cleared).map(p => p.ledger_id);
                return [...depIds, ...payIds];
            },

            submitFinish() {
                if (Math.abs(this.difference) > 0.01) {
                    window.showToast('Selisih belum 0. Cek kembali transaksi.', 'error');
                    return;
                }
                
                window.confirmDialog({
                    title: 'Selesaikan Rekonsiliasi?',
                    text: 'Pastikan data sudah benar. Periode ini akan dikunci.',
                    icon: 'warning',
                    confirmButtonText: 'Ya, Selesaikan',
                    cancelButtonText: 'Batal'
                }).then((r) => {
                    if(r.isConfirmed) document.getElementById('finish-recon-form').submit();
                });
            },

            // Formatters
            formatRupiah(num) {
                return 'Rp ' + new Intl.NumberFormat('id-ID', { minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(num);
            },
            formatNumber(num) {
                return new Intl.NumberFormat('id-ID').format(num);
            },
            formatDate(dateString) {
                if(!dateString) return '-';
                const date = new Date(dateString);
                return date.toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' });
            }
        }));
    });
</script>
@endpush

@endsection